pool:
  vmImage: 'windows-2019'

steps:
- task: SonarCloudPrepare@1
  displayName: 'Prepare Code Analysis'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'off-sync'
    projectKey: 'off-sync_mapping-practises'
    projectName: 'Off-Sync.Com Mapping Practises'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: build
    arguments: '--configuration Debug'

- task: SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'
  inputs: {}

- task: SonarCloudPublish@1
  displayName: 'Publish Code Analysis'
  inputs: {}

- task: DotNetCoreCLI@2
  displayName: 'Pack OffSync.Mapping.Practises'
  inputs:
    command: pack
    arguments: '--configuration Release'
    projects: 'src/OffSync.Mapping.Practises/OffSync.Mapping.Practises.csproj'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
