trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: Release
  projectToPack: src/OffSync.Mapping.Practises/OffSync.Mapping.Practises.csproj

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '$(projectToPack)'

- task: PublishBuildArtifacts@1
